# Generated by Django 5.0.3 on 2025-09-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_scanhistory_reasons_alter_scanhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanhistory',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
