# Generated by Django 5.0.3 on 2025-09-20 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_alter_scanhistory_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanhistory',
            old_name='scanned_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='scanhistory',
            name='reasons',
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='features_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='result',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
